services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_WEBSERVER_PORT: 8088
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_ADMIN_USERNAME: admin
      SUPERSET_ADMIN_PASSWORD: admin
      SUPERSET_ADMIN_EMAIL: admin@superset.com
      SECRET_KEY: 'JZYE1tXSjEje7ESXd5rcZHiSU3wYofeckvz5TUXfLziWj8mRVtXVRzA'
    volumes:
      - ./superset:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ./database_config.py:/app/pythonpath/database_config.py
    depends_on:
      - postgres
    command:
      - sh
      - -c
      - |
        pip install flask-cors psycopg2-binary &&
        superset db upgrade &&
        superset fab create-admin --username admin --password admin --email admin@superset.com --firstname admin --lastname admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
    networks:
      - superset_network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mbatha45
      POSTGRES_DB: medicines
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - superset_network

volumes:
  postgres_data:

networks:
  superset_network:
    driver: bridge
